# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it,
# run "uv run tox" from this directory.

[tox]
envlist = ruff,doctests,py{36,311,312,313,314},cov
deps = -rrequirements.txt
skip_missing_interpreters = true

[testenv:ruff]
deps =
    ruff
commands =
    ruff check .
    ruff format --check .

[testenv:doctests]
# only run doctest on main modules
commands =
    py.test --doctest-modules openqa_review/
deps = -rrequirements.txt
    pytest
    pytest-doc

[testenv:cov]
# necessary to make cov find the .coverage file
# see http://stackoverflow.com/a/34706770/5031322
usedevelop = true
# Ignore exit code of first command as this will always fail
commands =
    - py.test --cov=openqa_review --doctest-modules openqa_review/
    py.test --cov=openqa_review --cov-append
deps = -rrequirements.txt
    pytest
    pytest-cov
    pytest-mock

[testenv]
commands =
    py.test {posargs}
deps = -rrequirements.txt
    pytest
    pytest-mock
