# Copyright SUSE LLC
# SPDX-License-Identifier: MIT
"""HTTP browser abstraction for fetching and caching openQA web content.

Provides authenticated HTTP access to openQA instances with support for
local disk caching, retry logic, and BeautifulSoup-based HTML parsing.
"""

from __future__ import annotations

import errno
import json
import logging
import ssl
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, cast
from urllib.parse import quote, unquote, urljoin, urlparse

import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from sortedcontainers import SortedDict
from urllib3.util.retry import Retry

try:
    import OpenSSL

    _has_openssl = True
except ImportError:
    _has_openssl = False

if TYPE_CHECKING:
    import argparse

logging.basicConfig()
log = logging.getLogger(sys.argv[0] if __name__ == "__main__" else __name__)
logging.captureWarnings(capture=True)  # see https://urllib3.readthedocs.org/en/latest/security.html#disabling-warnings

JsonType = str | int | float | bool | list | dict | None

REQUEST_TIMEOUT = 30
BUGZILLA_BUG_NOT_FOUND_CODE = 101


class DownloadError(Exception):
    """Raised when an HTTP request or cache read fails unrecoverably.

    Used as the common base for all fetch failures so callers can catch
    a single exception type regardless of whether the failure came from
    a live HTTP request or a simulated load from disk.
    """


class CacheNotFoundError(DownloadError):
    """Raised when a cached file is missing in --load mode.

    In --load mode the browser never makes real HTTP requests; it reads
    previously saved files instead.  When the expected file does not exist
    this error is raised to mirror the behaviour of a failed live request,
    allowing callers to handle both cases uniformly.
    """


class BugzillaError(Exception):
    """Raised when the Bugzilla JSON-RPC API returns an error object.

    Bugzilla embeds errors inside a successful HTTP 200 response as
    ``{"error": {"code": <int>, "message": "<str>"}}``.  This exception
    captures all three identifiers so the caller can inspect the numeric
    code when deciding whether to retry or propagate.
    """

    def __init__(self, url: str, code: int, msg: str) -> None:
        """Store the URL, numeric error code, and message from the Bugzilla response."""
        self.url = url
        self.code = code
        self.message = msg

    def __str__(self) -> str:
        """Return a human-readable error string including URL, code, and message."""
        return f"Error retrieving '{self.url}': code={self.code} msg={self.message}'"


class BugNotFoundError(BugzillaError):
    """Raised when Bugzilla returns error code 101 (bug does not exist).

    Separating this from the generic BugzillaError lets callers silently
    skip stale or invalid bug references without masking real API failures.
    """


def url_to_filename(url: str) -> str:
    """Convert URL to a valid, unambiguous filename.

    >>> url_to_filename("http://openqa.opensuse.org/tests/foo/3")
    'http%3A::openqa.opensuse.org:tests:foo:3'
    """
    return quote(url).replace("/", ":")


def filename_to_url(name: str) -> str:
    """Convert filename generated by 'url_to_filename' back to valid URL.

    >>> str(filename_to_url("http%3A::openqa.opensuse.org:tests:foo:3"))
    'http://openqa.opensuse.org/tests/foo/3'
    """
    return unquote(name.replace(":", "/"))


class Browser:
    """HTTP client for openQA instances with caching, retry, and Bugzilla RPC support.

    Wraps ``requests`` to provide three fetch modes controlled by the ``args``
    namespace passed at construction time:

    - **live** (default): real HTTP requests with exponential-backoff retries.
    - **--save**: live fetch + writes each response to disk under ``save_dir``
      for later replay.
    - **--load**: reads responses from disk under ``load_dir`` instead of making
      any network calls; useful for reproducible tests or offline report runs.

    An in-memory dict cache is always active on top of these modes to avoid
    redundant requests within a single run.
    """

    def __init__(
        self,
        args: argparse.Namespace,
        root_url: str,
        auth: tuple[str, str] | None = None,
        headers: dict[str, str] | None = None,
        api_key: str | None = None,
    ) -> None:
        """Set up the browser from a parsed argument namespace and a base URL.

        Reads ``save``, ``load``, ``load_dir``, ``save_dir``, ``dry_run``, and
        ``retries`` from ``args`` if present, falling back to safe defaults so
        the class can be constructed with a minimal or empty namespace.

        ``root_url`` is used to resolve relative paths (those starting with
        ``/``) into absolute URLs.  ``auth`` is passed directly to
        ``requests`` as HTTP Basic credentials.  ``api_key`` is injected as
        ``Bugzilla_api_key`` into Bugzilla JSON-RPC calls when set.

        A ``User-Agent`` header identifying openqa-review is always added to
        ``headers`` so server logs can attribute the traffic correctly.
        """
        self.save = args.save if hasattr(args, "save") else False
        self.load = args.load if hasattr(args, "load") else False
        self.load_dir = args.load_dir if hasattr(args, "load_dir") else "."
        self.save_dir = args.save_dir if hasattr(args, "save_dir") else "."
        self.dry_run = args.dry_run if hasattr(args, "dry_run") else False
        self.retries = args.retries if hasattr(args, "retries") else 7
        self.root_url = root_url
        self.auth = auth
        self.api_key = api_key
        self.headers = {**(headers or {}), "User-Agent": "openqa-review (https://os-autoinst.github.io/openqa_review)"}
        self.cache = {}

    def get_soup(self, url: str) -> BeautifulSoup:
        """Fetch ``url`` and return the parsed HTML as a BeautifulSoup tree.

        Use this for openQA HTML pages where you need to navigate the DOM.
        For JSON API endpoints use ``get_json`` instead.
        """
        if not url:
            err = "url can not be None"
            raise ValueError(err)
        return BeautifulSoup(cast("str", self.get_page(url)), "html.parser")

    def get_json(self, url: str, *, cache: bool = True) -> JsonType:
        """Fetch ``url`` and return the body decoded as a Python object.

        Thin wrapper around ``get_page`` with ``as_json=True``.  Pass
        ``cache=False`` when the endpoint returns data that changes between
        calls within the same run (e.g. paginated results or live status).
        """
        return self.get_page(url, as_json=True, cache=cache)

    def get_page(self, url: str, *, as_json: bool = False, cache: bool = True) -> JsonType:
        """Fetch ``url`` and return its content, honouring the active fetch mode.

        Resolution order:
        1. **In-memory cache** - returned immediately if the URL was already
           fetched in this run and ``cache=True``.
        2. **Disk cache** (``--load`` mode) - reads the file written by a
           previous ``--save`` run; raises ``CacheNotFoundError`` if the file
           is absent so callers can treat it like a failed HTTP request.
        3. **Live HTTP** - delegates to ``_get`` with retry logic.

        After a live or disk fetch the result is written to the in-memory cache
        and, when ``--save`` is active, persisted to disk so it can be replayed
        later.  The on-disk filename is derived from the URL via
        ``url_to_filename`` so each URL maps to exactly one file.
        """
        if url in self.cache and cache:
            log.info("Loading content instead of URL %s from in-memory cache", url)
            return json.loads(self.cache[url]) if as_json else self.cache[url]
        filename = url_to_filename(url)
        if self.load and cache:
            log.info("Loading content instead of URL %s from filename %s", url, filename)
            try:
                with (Path(self.load_dir) / filename).open(encoding="utf-8") as f:
                    raw = f.read()
            except OSError as e:
                if e.errno == errno.ENOENT:
                    msg = f"Request to {url} was not successful, file {filename} not found"
                    log.info(msg)
                    # as 'load' simulates downloading we also have to simulate an appropriate error
                    raise CacheNotFoundError(msg) from e
                # pragma: no cover
                raise
            content = json.loads(raw) if as_json else raw
        else:  # pragma: no cover
            absolute_url = url if not url.startswith("/") else urljoin(str(self.root_url), str(url))
            content = self._get(absolute_url, as_json=as_json)
        raw = json.dumps(content) if as_json else cast("str", content)
        if self.save:
            log.info("Saving content instead from URL %s from filename %s", url, filename)
            with (Path(self.save_dir) / filename).open("w", encoding="utf-8") as f:
                f.write(raw)
        self.cache[url] = raw
        return content

    def _get(self, url: str, *, as_json: bool = False) -> JsonType:  # pragma: no cover
        """Perform the actual HTTP GET with retry and SSL error enrichment.

        Mounts a ``HTTPAdapter`` with exponential back-off retrying on transient
        server errors (429, 500, 502, 503, 504).  SSL errors get special
        treatment: if ``pyOpenSSL`` is installed the certificate's issuer and
        fingerprints are extracted and included in the ``DownloadError`` message
        to help diagnose corporate-proxy or self-signed cert issues without
        having to run a separate openssl command.  Without pyOpenSSL the original
        SSL error is re-raised unchanged.
        """
        retries = Retry(total=self.retries, backoff_factor=2, status_forcelist=[429, 500, 502, 503, 504])
        http = requests.Session()
        parsed_url = urlparse(url)
        http.mount(f"{parsed_url.scheme}://", HTTPAdapter(max_retries=retries))

        try:
            r = http.get(url, auth=self.auth, timeout=REQUEST_TIMEOUT, headers=self.headers)
        except requests.exceptions.SSLError as e:
            if not _has_openssl:
                raise e from None
            # as we go one layer deeper from http now, we're just interested in the hostname
            server_name = parsed_url.netloc
            cert = ssl.get_server_certificate((server_name, 443)).encode()
            x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
            issuer_components = x509.get_issuer().get_components()
            # we're only interested in the b'O'rganizational unit
            issuers = filter(lambda component: component[0] == b"O", issuer_components)
            issuer = next(issuers)[1].decode("utf-8", "ignore")
            sha1digest = x509.digest("sha1").decode("utf-8", "ignore")
            sha256digest = x509.digest("sha256").decode("utf-8", "ignore")
            msg = (
                f'Certificate for "{server_name}" from "{issuer}"'
                f" (sha1: {sha1digest}, sha256 {sha256digest}) is not trusted by the system"
            )
            log.exception(msg)
            raise DownloadError(msg) from e
        except requests.exceptions.ConnectionError as e:
            msg = f"Request to {url} was not successful after {retries.total} retries: {e!s}"
            log.warning(msg)
            raise DownloadError(msg) from e
        except requests.exceptions.ChunkedEncodingError as e:
            msg = f"Request to {url} was not successful: {e!s}"
            log.warning(msg)
            raise DownloadError(msg) from e
        try:
            r.raise_for_status()
        except requests.exceptions.HTTPError as e:
            msg = f"Request to {url} failed: {e!s}"
            log.warning(msg)
            raise DownloadError(msg) from e
        return Browser._decode_content(url, r.content.decode("utf-8"), as_json=as_json)

    @staticmethod
    def _decode_content(url: str, raw: str, *, as_json: bool = False) -> JsonType:
        """Decode ``raw`` as JSON when requested, wrapping parse errors as ``DownloadError``.

        Kept separate from ``_get`` so that both live responses and disk-cached
        content go through the same decoding path and produce consistent errors.
        """
        try:
            content = json.loads(raw) if as_json else raw
        except json.decoder.JSONDecodeError as e:
            msg = f'Unable to decode JSON for {url}: {e!s} (Content was: "{raw}")'
            log.warning(msg)
            raise DownloadError(msg) from e
        return content

    def _params_with_login(self, params: dict[str, JsonType]) -> dict[str, JsonType]:
        """Inject the Bugzilla API key into ``params`` if one was configured.

        The key is sent as ``Bugzilla_api_key`` which is the field name
        expected by the Bugzilla JSON-RPC API for token-based authentication,
        avoiding the need to pass plain username/password credentials.
        """
        if self.api_key:
            params["Bugzilla_api_key"] = self.api_key
        return params

    def json_rpc_get(self, url: str, method: str, params: dict[str, JsonType], *, cache: bool = True) -> JsonType:
        """Call a Bugzilla JSON-RPC method via GET with automatic retry on transient errors.

        Parameters are serialised into the query string so the full URL is
        cacheable.  A ``SortedDict`` is used for deterministic parameter
        ordering, which ensures the same URL is generated across calls and
        cache hits work correctly.

        Bugzilla error code 101 (bug not found) is raised immediately as
        ``BugNotFoundError`` without retrying because the bug will not appear
        between retries.  All other error codes are retried up to ``self.retries``
        times with exponential back-off before raising ``BugzillaError``.
        """
        absolute_url = url if not url.startswith("/") else urljoin("http://dummy/", str(url))
        params = self._params_with_login(params)
        get_params = SortedDict({"method": method, "params": json.dumps([params])})
        prepared_url = requests.Request("GET", absolute_url, params=get_params).prepare().url
        if prepared_url is None:  # pragma: no cover
            msg = "Failed to prepare request URL"
            raise ValueError(msg)
        get_url = prepared_url.replace("http://dummy", "")
        error = None
        for i in range(1, self.retries):
            response = self.get_json(get_url, cache=cache)
            if not isinstance(response, dict):
                continue
            if error := response.get("error"):
                if error["code"] == BUGZILLA_BUG_NOT_FOUND_CODE:
                    raise BugNotFoundError(get_url, error["code"], error["message"])
                sleep_time = 2**i
                log.warning(
                    "Bugzilla returned error %s accessing %s, retrying in %ss try %s",
                    error["code"],
                    get_url,
                    sleep_time,
                    i,
                )
                time.sleep(sleep_time)
                continue
            return response
        if error:  # pragma: no cover
            raise BugzillaError(get_url, error["code"], error["message"])
        return None

    def json_rpc_post(self, url: str, method: str, params: dict[str, JsonType]) -> dict[str, JsonType] | None:
        """Call a Bugzilla JSON-RPC method via POST, used for write operations.

        Unlike ``json_rpc_get``, responses are never cached because POST calls
        mutate server state.  In ``dry_run`` mode the request is skipped entirely
        and an empty dict is returned so callers can proceed without side effects.

        Retries on ``ConnectionError`` only - HTTP-level errors from
        ``raise_for_status`` are not caught here and will propagate to the caller.
        Returns ``None`` when the server responds with an empty body.
        """
        params = self._params_with_login(params)
        if self.dry_run:
            log.warning("NOT sending '%s' request to '%s' with params %r", method, url, params)
            return {}
        # pragma: no cover
        absolute_url = url if not url.startswith("/") else urljoin(str(self.root_url), str(url))
        data = json.dumps({"method": method, "params": [params]})
        for i in range(1, self.retries):
            try:
                headers = self.headers.copy()
                headers["content-type"] = "application/json"
                r = requests.post(absolute_url, data=data, auth=self.auth, headers=headers, timeout=REQUEST_TIMEOUT)
                r.raise_for_status()
            except requests.exceptions.ConnectionError:
                log.info("Connection error encountered accessing %s, retrying try %s", absolute_url, i)
                continue
            break
        else:
            msg = f"Request to {absolute_url} was not successful after multiple retries, giving up"
            log.warning(msg)
            return None
        return r.json() if r.text else None

    def json_rest(self, url: str, method: str, data: dict[str, JsonType]) -> JsonType:
        """Send a JSON REST request using an arbitrary HTTP method.

        Unlike ``json_rpc_post``, this is not Bugzilla-specific and can target
        any REST endpoint.  In ``dry_run`` mode only non-GET requests are
        suppressed; GET requests always execute because they are read-only.

        No retry logic is applied here - the caller is responsible for
        handling transient failures if needed.  Returns ``None`` on an empty
        response body.
        """
        if self.dry_run and method.upper() != "GET":
            log.warning("NOT sending '%s' request to '%s' with params %r", method, url, data)
            return {}
        # pragma: no cover
        absolute_url = url if not url.startswith("/") else urljoin(str(self.root_url), str(url))
        body = json.dumps(data)
        headers = self.headers.copy()
        headers["content-type"] = "application/json"
        r = requests.request(
            method,
            absolute_url,
            data=body,
            headers=headers,
            timeout=REQUEST_TIMEOUT,
        )
        r.raise_for_status()
        return r.json() if r.text else None


def add_browser_args(parser: argparse.ArgumentParser) -> None:
    """Register Browser-related CLI arguments on ``parser``.

    ``--save`` and ``--load`` are mutually exclusive: you can capture a live
    run to disk or replay a captured run, but not both at once.  The directory
    arguments default to the current working directory.  Call this from any
    entry-point that constructs a ``Browser`` so all fetch-mode options are
    consistently available to the user.
    """
    load_save = parser.add_mutually_exclusive_group()
    load_save.add_argument(
        "--save",
        action="store_true",
        help="""Save downloaded webpages and test data to local
                           folder. Name is autogenerated. This could be useful
                           for test investigation, loading same results for
                           another run of report generation with "--load" or
                           debugging""",
    )
    load_save.add_argument(
        "--load",
        action="store_true",
        help="""Use previously downloaded webpages and data.
                           See '--save'.""",
    )
    parser.add_argument(
        "--load-dir",
        default=".",
        help="""The directory to read cache files from when
                        using '--load'.""",
    )
    parser.add_argument(
        "--save-dir",
        default=".",
        help="""The directory to write cache files to when
                        using '--save'.""",
    )
    parser.add_argument("--retries", default=7, type=int, help="""Number of retries on failed remote requests.""")
