#!/usr/bin/python3
# Copyright SUSE LLC
# SPDX-License-Identifier: MIT

"""Review helper script for openQA.

# Inspiration

We want to gather information about the build status and condense this into a
review report.

E.g.

1. Go to the openQA Dashboard and select the latest build of the product you
want to review.

2. Walk through all red testcases for the product for all arches.

 - fix the needle
 - report a bug against openQA
 - report a bug against the product


Also review still failing test cases.

3. Add a comment to the overview page of the reviewed product using the
template generated by this script


# What it does

On calling the script it parses openQA status reports from openQA server
webpages and generates markdown text usable as template for review reports.

So far it is save to call it as it does not use or need any kind of
authentication and only reads the webpage. No harm should be done :-)

## feature list

 - Command line options with different modes, e.g. for markdown report generation
 - Strip optional "Build" from build number when searching for last reviewed
 - Support differing tests in test rows
 - Loading and saving of cache files (e.g. for testing)
 - Skip over '(reference ...)' searching for last reviewed
 - Yield last finished in case of no reviewed found in comments
 - Add proper handling for non-number build number, e.g. for 'SLE HA'
 - Tests to ensure 100% statement and branch coverage
 - Coverage analysis and test
 - Option to compare build against last reviewed one from comments section
 - Extended '--job-groups' to also accept regex terms
 - Add notice in report if architectures are not run at all
 - Support for explicit selection of builds not in job group display anymore
 - Add optional link to previous build for comparison for new issues
 - Option to specify builds for comparison
 - Support both python version 2 and 3
 - Human friendly progress notification and wait spinner
 - Accept multiple entries for '--job-group(-urls)'
 - Ensure report entries are in same alphabetical order with OrderedDict
 - tox.ini: Local tests, doctests, check with flake8
 - Generate version based on git describe
 - Add support to parse all job groups


# How to use

Just call it and see what happens or call this file with option '--help'.


# Design decisions

The script was designed to be a webscraping script for the following reasons

 * It should as closely resemble what the human review user encounters and not
   use any "hidden API" magic
 * "proof of concept": Show that it is actually possible using webscraping on
   a clean web design as openQA provides :-)
 * Do not rely on the annoyingly slow login and authentication redirect
   mechanism used on openqa.opensuse.org as well as openqa.opensuse.org


Alternatives could have been and still are for further extensions or reworks:

 * Use of https://github.com/os-autoinst/openQA-python-client and extend on
   that
 * Directly include all necessary meta-reports as part of openQA itself
 * Use REST or websockets API instead of webscraping


"""

from __future__ import annotations

import argparse
import codecs
import datetime
import logging
import re
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path
from typing import TYPE_CHECKING, Any, NamedTuple, cast

from configparser import ConfigParser, NoSectionError, NoOptionError  # isort:skip can not make isort happy here
from string import Template
from urllib.parse import parse_qs, quote, unquote, urlencode, urljoin, urlparse

from bs4 import BeautifulSoup
from requests.exceptions import HTTPError
from sortedcontainers import SortedDict

sys.path.insert(0, str(Path(__file__).parent.parent.resolve()))

from .browser import Browser, DownloadError, BugNotFoundError, JsonType, add_browser_args  # isort:skip

if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Callable, Generator, Iterable, KeysView, Sequence

    from bs4 import BeautifulSoup as BeautifulSoupType
    from bs4 import Tag as TagType
    from sortedcontainers import SortedDict as SortedDictType


# treat humanfriendly as optional dependency
humanfriendly_available = False
try:
    from humanfriendly.terminal.spinners import AutomaticSpinner
    from humanfriendly.text import pluralize

    humanfriendly_available = True
except ImportError:  # pragma: no cover

    def pluralize(_1: int, _2: str, plural: str) -> str:  # pragma: no cover
        """Return plural form as fallback when humanfriendly is unavailable."""
        return plural


# minimum number of days an issue is unchanged before putting a reminder comment
MIN_DAYS_UNCHANGED = 14

# ID of feedback status in Redmine
REDMINE_STATUS_ID_FEEDBACK = 4

# threshold constants for status badge determination
STATUS_AMBER_MAX_STILL_FAILING = 5
VERBOSE_TEST_REF_BUILD = 2
VERBOSE_TEST_CHANGES = 3
VERBOSE_LEVEL_DEBUG = 4
MIN_BUILDS_REQUIRED = 2

# default regex to skip soft-failed reminders
NO_REMINDER_REGEX = re.compile(r"WONTFIX|NO_REMINDER")

logging.basicConfig()
log = logging.getLogger(sys.argv[0] if __name__ == "__main__" else __name__)
logging.captureWarnings(capture=True)  # see https://urllib3.readthedocs.org/en/latest/security.html#disabling-warnings

config = ConfigParser()


class BrowserSet(NamedTuple):
    """Holds the three browser instances used in architecture report generation."""

    progress_browser: Browser | None
    bugzilla_browser: Browser | None
    test_browser: Browser | None


class TestContext(NamedTuple):
    """Holds the extracted context from a test details page."""

    group: str
    build: str
    scenario: str
    latest_link: str
    previous_results_list: list


CONFIG_PATH = str(Path("~/.openqa_reviewrc").expanduser())
CONFIG_USAGE = """
You are missing the mandatory configuration file with the proper format.
Example:
[product_issues]
system = bugzilla
# if username and password are not defined here, they will be stored in your
# local keyring if found
#username = user
#password = secret
# newer Bugzilla versions use an API key instead of username and password
#api_key = token
base_url = https://apibugzilla.suse.com
report_url = https://bugzilla.suse.com

# for correct generation of issue reporting links add mappings from openQA
# group IDs to product names in the corresponding issue tracker, e.g.
# necessary for bugzilla
[product_issues:https://openqa.opensuse.org:product_mapping]
25 = openSUSE Tumbleweed

[product_issues:http://openqa.opensuse.org:component_mapping]
installation-bootloader = Bootloader

[test_issues]
system = redmine
#api_key = 0123456789ABCDEF
report_url = https://progress.opensuse.org/projects/openqatests/issues/new
"""


openqa_review_report_product_template = Template(
    """
**Date:** $now
**Build:** $build
$common_issues
---
$arch_report
"""
)  # ignore trailing whitespace for forced line breaks

todo_review_template = Template(
    """
**TODO: review**
$new_issues$existing_issues"""
)

# TODO(okurz): don't display sections if empty
openqa_review_report_arch_template = Template(
    """
**Arch:** $arch
**Status: $status_badge**
$skipped_tests$new_product_issues$existing_product_issues$new_openqa_issues$existing_openqa_issues$todo_issues"""
)

openqa_issue_comment = Template(
    """
This is an autogenerated message for openQA integration by the openqa_review script:

This bug is still referenced in a failing openQA test: $name
$url

To prevent further reminder comments one of the following options should be followed:
1. The test scenario is fixed by applying the bug fix to the tested product or the test is adjusted
2. The openQA job group is moved to "Released" or "EOL" (End-of-Life)
3. The bugref in the openQA scenario is removed or replaced, e.g. `label:wontfix:boo1234`
4. For "record_soft_failure" references the reference is removed or matches the pattern '$no_reminder_pattern'

Expect the next reminder at the earliest in $time_next days if nothing changes in this ticket.
"""
)

status_badge_str = {
    "GREEN": '<span style="color: green;">Green</span>',
    "AMBER": '<span style="color: #FFBF00;">Amber</span>',
    "RED": '<span style="color: red;">Red</span>',
}


class NotEnoughBuildsError(Exception):
    """Not enough finished builds found."""


def parse_summary(details: BeautifulSoupType) -> dict[str, int]:
    """Parse and return build summary as dict."""
    summary_tag = details.find(id="summary")
    if summary_tag is None:  # pragma: no cover
        msg = "Could not find summary tag with id='summary'"
        raise ValueError(msg)
    return {str(i.previous).strip().rstrip(":").lower(): int(i.text) for i in summary_tag.find_all(class_="badge")}


change_state = {
    ("result_passed", "result_failed"): "NEW_ISSUE",
    ("result_softfailed", "result_failed"): "NEW_ISSUE",
    ("result_passed", "result_softfailed"): "NEW_SOFT_ISSUE",
    ("result_failed", "result_passed"): "FIXED",  # fixed, maybe spurious, false positive
    ("result_softfailed", "result_passed"): "FIXED",
    ("result_failed", "result_failed"): "STILL_FAILING",  # still failing or partial improve, partial degrade
    ("result_softfailed", "result_softfailed"): "STILL_SOFT_FAILING",
    ("result_failed", "result_softfailed"): "IMPROVED",
    ("result_passed", "result_passed"): "STABLE",  # ignore or crosscheck if not false positive
}

soft_fail_states = ["STILL_SOFT_FAILING", "NEW_SOFT_ISSUE", "IMPROVED"]

interesting_states_names = [i for i in set(change_state.values()) if i != "STABLE"] + ["INCOMPLETE"]

issue_tracker = {  # pragma: no branch
    "bsc": lambda i: f"https://bugzilla.suse.com/show_bug.cgi?id={i}",
    "boo": lambda i: f"https://bugzilla.opensuse.org/show_bug.cgi?id={i}",
    "poo": lambda i: f"https://progress.opensuse.org/issues/{i}",
    "bgo": lambda i: f"https://bugzilla.gnome.org/show_bug.cgi?id={i}",
}

bugref_regex = "(poo|boo|bsc|bgo)#?([0-9]+)"


def status(entry: TagType) -> str:
    """Return test status from entry, e.g. 'result_passed'."""
    i_tag = entry.i
    if i_tag is None:  # pragma: no cover
        msg = "Could not find <i> tag in entry for status"
        raise ValueError(msg)
    return next(s for s in cast("list", i_tag["class"]) if re.search(r"(state|result)_", s))


def get_build_nr(url: str) -> str:
    """Extract and return the build number from a URL."""
    m = re.search(r"build=([^&]*)", url)
    if m is None:  # pragma: no cover
        msg = f"Could not find build number in URL: {url}"
        raise ValueError(msg)
    return unquote(m.groups()[0])


def get_failed_needles(m: TagType) -> list[str]:
    """Return list of failed needle names from a test result entry."""
    title = m.get("title") if hasattr(m, "get") else None
    if not title:
        return []
    return [str(i.text) for i in BeautifulSoup(str(title), "html.parser").find_all("li")]


def get_test_details(entry: TagType) -> dict[str, Any]:
    """Return href and failed module details for a test entry."""
    failedmodules = entry.find_all(class_="failedmodule")

    def find_module_href(m: TagType) -> str:
        # optional fallback to old openQA code, 4.5, pre bootstrap4
        try:
            return str(m["href"])
        except KeyError as e:
            a_tag = m.a
            if a_tag is None:  # pragma: no cover
                msg = "Could not find <a> tag in failedmodule entry"
                raise ValueError(msg) from e
            return str(a_tag["href"])

    entry_a = entry.a
    if entry_a is None:  # pragma: no cover
        msg = "Could not find <a> tag in test entry"
        raise ValueError(msg)
    return {
        "href": str(entry_a["href"]),
        "failedmodules": [
            {"href": find_module_href(m), "name": m.text.strip(), "needles": get_failed_needles(m)}
            for m in failedmodules
        ],
    }


def get_test_bugref(entry: TagType) -> dict[str, str]:
    """Return bugref info dict from a test result entry, or empty dict if absent."""
    bugref = entry.find(id=re.compile(r"^bug-"))
    if not bugref:
        return {}
    bugref_i = bugref.i
    if bugref_i is None:  # pragma: no cover
        msg = "Could not find <i> tag in bugref element"
        raise ValueError(msg)
    i_title = str(bugref_i["title"])
    reference = re.search(r"\S+#([0-9]+)", i_title)
    ref_str = reference.group() if reference else f"(unknown bugref in {i_title})"
    # work around openQA providing incorrect URLs (e.g. following whitespace)
    bugref_a = bugref.a
    if bugref_a is None:  # pragma: no cover
        msg = "Could not find <a> tag in bugref element"
        raise ValueError(msg)
    return {"bugref": ref_str, "bugref_href": str(bugref_a["href"]).strip()}


def get_state(cur: TagType, prev_dict: dict[str, TagType]) -> tuple[str, dict[str, Any]]:
    """Return change_state for 'previous' and 'current' test status html-td entries."""
    # TODO(okurz): instead of just comparing the overall state we could check if
    # failing needles differ
    cur_id = str(cur["id"])
    state_dict: dict[str, Any] = {}
    try:
        prev = prev_dict[cur_id]
        state_dict["state"] = change_state[status(prev), status(cur)]
        # add more details, could be skipped if we don't have details
        prev_a = prev.find("a")
        if prev_a is None:  # pragma: no cover
            msg = "Could not find <a> tag in previous test entry"
            raise ValueError(msg)
        state_dict["prev"] = {"href": str(prev_a["href"])}
    except KeyError:
        # if there is no previous or it was never completed we assume passed to mark new failing test as 'NEW_ISSUE'
        state_dict["state"] = change_state.get(("result_passed", status(cur)), "INCOMPLETE")
    state_dict.update(get_test_details(cur))
    state_dict.update(get_test_bugref(cur))
    return cur_id, state_dict


def get_arch_state_results(
    arch: str,
    current_details: BeautifulSoupType,
    previous_details: BeautifulSoupType,
    *,
    output_state_results: bool = False,
) -> SortedDictType:
    """Return SortedDict of interesting test state changes for the given arch."""
    result_re = re.compile(arch + "_")
    test_results = current_details.find_all("td", id=result_re)
    test_results_previous = previous_details.find_all("td", id=result_re)
    # find differences from previous to current (result_X)
    test_results_dict = {str(i["id"]): i for i in test_results}
    skipped = get_skipped_dict(arch, current_details)

    test_results_previous_dict = {str(i["id"]): i for i in test_results_previous if str(i["id"]) in test_results_dict}
    states = SortedDict(get_state(v, test_results_previous_dict) for v in test_results_dict.values())

    # intermediate step:
    # - print report of differences
    interesting_states = SortedDict({k.split(arch + "_")[1]: v for k, v in states.items() if v["state"] != "STABLE"})

    if output_state_results:
        log.debug("arch: %s", arch)
        for state in interesting_states_names:
            names = ", ".join(k for k, v in interesting_states.items() if v["state"] == state)
            log.debug("\n%s:\n\t%s\n", state, names)
    interesting_states.update({"skipped": skipped})
    return interesting_states


def absolute_url(root: str, v: BeautifulSoupType | dict[str, Any]) -> str:
    """Return absolute URL by joining root with href from v."""
    return urljoin(root, str(v["href"]))


def progress_browser_factory(args: argparse.Namespace) -> Browser:
    """Create and return a Browser configured for Redmine/progress access."""
    return Browser(
        args,
        root_url="",
        headers={"X-Redmine-API-Key": config.get("test_issues", "api_key")},
    )


def bugzilla_browser_factory(args: argparse.Namespace) -> Browser:
    """Create and return a Browser configured for Bugzilla access."""
    auth: tuple[str, str] | None = None
    # We need either an API key or login & password
    if not config.has_option("product_issues", "api_key"):
        auth = (
            config.get("product_issues", "username", fallback=""),
            config.get("product_issues", "password", fallback=""),
        )
    return Browser(
        args,
        config.get("product_issues", "base_url"),
        auth,
        api_key=config.get("product_issues", "api_key", fallback=None),
    )


def issue_listing(
    header: str, issues: Sequence[IssueEntry | str], *, show_empty: bool = True, no_headers: bool = False
) -> str:
    r"""Generate one issue listing section.

    @param header: Header string for section
    @param issues: List of IssueEntry objects
    @param show_empty: show empty sections if True and issues are an empty string

    >>> issue_listing("***new issues:***", "None")
    '\n***new issues:***\n\nNone\n'
    >>> issue_listing("***Common issues:***", "")
    '\n***Common issues:***\n\n\n'
    >>> issue_listing("***no issues***", "", show_empty=False)
    ''
    """
    if not show_empty and len(issues) == 0:
        return ""
    if no_headers:
        return "".join(f"* {header} {i.stringify()}\n" for i in cast("list[IssueEntry]", issues))
    return "\n" + header + "\n\n" + "".join(map(str, issues)) + "\n"


def common_issues(issues: str, *, show_empty: bool = True) -> str:
    """Return markdown-formatted common issues section."""
    if not show_empty and not issues:
        return ""
    return "\n" + "**Common issues:**" + "\n" + issues + "\n"


def issue_type(bugref: str) -> str:
    """Return 'openqa' for poo bugs, 'product' otherwise."""
    return "openqa" if bugref.startswith("poo#") else "product"


def issue_state(result_list: list[dict[str, Any]]) -> str:
    """Return 'existing' if any result was still failing, 'new' otherwise."""
    # if any result was still failing the issue is regarded as existing
    return "existing" if [i for i in result_list if re.match(r"(STILL|IMPROVED)", i["state"])] else "new"


def get_results_by_bugref(results: SortedDictType, args: argparse.Namespace) -> defaultdict[str, list[dict[str, Any]]]:
    """Group test results by bugref, returning a defaultdict of lists."""
    include_tags = ["STILL_FAILING", "NEW_ISSUE"]
    if args.include_softfails:
        include_tags += soft_fail_states

    # plain for-loop with append is most efficient:
    # https://stackoverflow.com/questions/11276473/append-to-a-dict-of-lists-with-a-dict-comprehension
    results_by_bugref = defaultdict(list)
    for k, v in results.items():
        if not re.match("(" + "|".join(include_tags) + ")", v["state"]):
            continue
        key = v["bugref"] if (args.bugrefs and "bugref" in v and v["bugref"]) else "todo"
        results_by_bugref[key].append(dict(v, name=k))
    return results_by_bugref


def set_status_badge(states: list[str]) -> str:
    """Determine status badge color based on issue counts."""
    # TODO(okurz): pretty arbitrary
    if states.count("NEW_ISSUE") == 0 and states.count("STILL_FAILING") <= 1:
        return "GREEN"
    # still failing and soft issues allowed; TODO(okurz): also arbitrary, just adjusted to test set
    if states.count("NEW_ISSUE") == 0 and states.count("STILL_FAILING") <= STATUS_AMBER_MAX_STILL_FAILING:
        return "AMBER"
    return "RED"


def find_builds(builds: dict[str, dict[str, Any]], running_threshold: float | str | None = 0) -> KeysView[str]:
    """Find finished builds, ignore still running or empty."""
    threshold = float(running_threshold) if running_threshold is not None else 0

    # filter out empty builds
    def non_empty(r: dict[str, Any]) -> bool:
        return r["total"] != 0 and r["total"] > r["skipped"] and not ("build" in r and r["build"] is None)

    builds = {build: result for build, result in builds.items() if non_empty(result)}
    finished = {
        build: result
        for build, result in builds.items()
        if not result["unfinished"] or (100 * float(result["unfinished"]) / result["total"]) <= threshold
    }

    log.debug("Found the following finished non-empty builds: %s", ", ".join(finished.keys()))
    if len(finished) < MIN_BUILDS_REQUIRED:
        msg = "not enough finished builds found"
        raise NotEnoughBuildsError(msg)
    return finished.keys()


def find_last_reviewed_build(comments: list[dict[str, Any]]) -> str:
    """Find last reviewed build within job group comments."""
    # Could also find previous one with a comment on the build status,
    # i.e. a reviewed finished build
    # The build number itself might be prefixed with a redundant 'Build' which we ignore
    build_re = re.compile(r"[bB]uild:(\*\*)? *(Build)?([\w@.]*)(.*reference.*)?(\*\*)?\r\n")
    # Assuming the most recent with a build number also has the most recent review
    for c in reversed(comments):
        match = build_re.search(c["text"])
        if match:
            last_reviewed = match.group(3)
            break
    return last_reviewed


def _try_zero_pad(part: str) -> str:
    """Return zero-padded numeric string or the original if not numeric."""
    try:
        return f"{int(part):020d}"
    except ValueError:
        return part


def mysort(x: str) -> list[str]:
    """Sort strings like build numbers with dashes and/or dots, e.g. 12-SP5-0456."""
    return [_try_zero_pad(part) for part in re.split(r"[-.]", x)]


def get_build_urls_to_compare(
    browser: Browser,
    job_group_url: str,
    builds: str = "",
    against_reviewed: str | None = None,
    running_threshold: float | str = 0,
) -> tuple[str, str]:
    """From the job group page get URLs for the builds to compare.

    @param browser: A browser instance
    @param job_group_url: forwarded to browser instance
    @param builds: Builds for which URLs should be retrieved as comma-separated pair, w/o the word 'Build'
    @param against_reviewed: Alternative to 'builds', which build to retrieve for comparison with last reviewed, can be
      'last' to automatically select the last finished
    @param running_threshold: Threshold of which percentage of jobs may still be running for the build to be considered
      'finished' anyway
    """
    job_group = cast("dict[str, Any]", browser.get_json(f"{job_group_url}.json"))

    def get_group_result() -> dict[str, Any]:
        try:
            results_list = cast("list", job_group["build_results"])
            return {i["key"]: i for i in results_list}
        except KeyError:
            log.debug("Reverting to old openQA behaviour before openQA#9b50b22")
            return cast("dict[str, Any]", job_group["result"])

    def build_url(build: str) -> str:
        r = get_group_result()
        b = r.get(build, next(iter(r.values())))
        build = b.get("build", build)
        # openQA introduced multi-distri support for the job groups with openQA#037ffd33
        distri_str = (
            f"distri={b['distri']}"
            if "distri" in b
            else "distri=" + "&distri=".join(sorted(cast("dict", b["distris"]).keys()))
        )
        gid = cast("dict[str, Any]", job_group["group"])["id"]
        return f"/tests/overview?{distri_str}&version={quote(b['version'])}&build={quote(build)}&groupid={gid}"

    finished_builds = find_builds(get_group_result(), running_threshold)
    # find last finished and previous one

    builds_to_compare = sorted(finished_builds, key=mysort, reverse=True)[0:2]

    if builds:
        # User has to be careful here. A page for non-existent builds is always
        # existent.
        builds_to_compare = builds.split(",")
        log.debug("Specified builds %s, parsed to %s", builds, ", ".join(builds_to_compare))
    elif against_reviewed:
        try:
            last_reviewed = find_last_reviewed_build(cast("list", job_group["comments"]))
            log.debug("Comparing specified build %s against last reviewed %s", against_reviewed, last_reviewed)
            build_to_review = builds_to_compare[0] if against_reviewed == "last" else against_reviewed
            builds_differ_too_much = len(build_to_review) > len(last_reviewed) + 1
        except (NameError, AttributeError, IndexError):
            log.info("No last reviewed build found for URL %s, reverting to two last finished", job_group_url)
        else:
            if not builds_differ_too_much:
                builds_to_compare = build_to_review, last_reviewed
            else:  # pragma: no cover
                log.info("No last reviewed build found for URL %s, reverting to two last finished", job_group_url)

    log.debug("Comparing build %s against %s", builds_to_compare[0], builds_to_compare[1])
    current_url, previous_url = map(build_url, builds_to_compare)
    log.debug("Found two build URLS, current: %s previous: %s", current_url, previous_url)
    return current_url, previous_url


def get_failed_module_details_for_report(f: dict[str, Any]) -> tuple[str, str, str]:
    """Return (name, url, details) tuple for the first failed module of a test result."""
    try:
        failed_module = f["failedmodules"][0]
    except IndexError:
        log.debug("%s does not have failed module, taking complete job.", f["href"])
        name = ""
        url = f["href"]
        details = ""
    else:
        name = failed_module["name"]
        url = failed_module["href"]
        details = f"\nwith failed needles: {failed_module['needles']}"
    return name, url, details


def _find_first_last(
    root_url: str, build: str, previous_results_list: list[tuple[str, dict[str, Any]]]
) -> tuple[str, str]:
    """Return (first_known_bad, last_good) strings from previous results."""
    good = re.compile(r"(?<=_)(passed|softfailed)")

    def build_link(v: dict[str, Any]) -> str:
        return f"[{v['build']}]({absolute_url(root_url, v['details'])})"

    first_known_bad = build + " (current job)"
    last_good = "(unknown)"
    for _k, v in previous_results_list:
        if good.search(v["status"]):
            last_good = build_link(v)
            break
        first_known_bad = build_link(v)
    return first_known_bad, last_good


def _build_issue_description(
    scenario: str, full_url_with_details: str, first_known_bad: str, last_good: str, latest_link: str
) -> str:
    """Build the markdown description for a new issue report."""
    return f"""### Observation

openQA test in scenario {scenario} fails in
{full_url_with_details}


## Reproducible

Fails since (at least) Build {first_known_bad}


## Expected result

Last good: {last_good} (or more recent)


## Further details

Always latest result in this scenario: [latest]({latest_link})
"""


def _lookup_component_and_product(
    root_url: str, test_details_page: BeautifulSoupType, url: str, module: str, group: str
) -> tuple[str, str]:
    """Look up the component and product from config for a given module."""
    config_section = f"product_issues:{root_url.rstrip('/')}:product_mapping"
    first_step_url = urljoin(str(url), "1/src")
    start_of_current_module = test_details_page.find("a", {"href": first_step_url})
    try:
        ancestor = cast("Any", start_of_current_module).parent.parent.parent.parent
        folder_icon = ancestor.find(class_="glyphicon-folder-open")
        module_folder = folder_icon.parent.text.strip()
    except AttributeError:  # pragma: no cover
        module_folder = ""
        log.warning("Could not find module folder on test details page searching for parents of %s", first_step_url)
    complete_module = module_folder + "-" + module
    component_config_section = f"product_issues:{root_url.rstrip('/')}:component_mapping"
    try:
        components_config_dict = dict(config.items(component_config_section))
        component = next(v for k, v in components_config_dict.items() if re.match(k, complete_module))
    except (NoSectionError, StopIteration) as e:  # pragma: no cover
        log.info(
            "No matching component found for module_folder '%s' and module name '%s' in config section '%s'",
            module_folder,
            module,
            e,
        )
        component = ""
    try:
        product = config.get(config_section, group)
    except NoOptionError as e:  # pragma: no cover
        log.info("%s. Reporting link for product will not work.", e)
        product = ""
    return component, product


def _get_test_context(root_url: str, test_details_page: BeautifulSoupType) -> TestContext:
    """Extract group, build, scenario, latest_link, previous_results_list from the test details page."""
    current_build_overview = urlparse(
        str(cast("Any", test_details_page.find(id="current-build-overview")).a["href"])
    ).query
    overview_params = parse_qs(current_build_overview)
    group = overview_params["groupid"][0]
    build = overview_params["build"][0]
    try:
        scenario_div: Any = cast("Any", test_details_page.find(class_="next_previous")).div.div
        scenario = re.findall(r"Next & previous results for (.*) \(", scenario_div.text)[0]
    except AttributeError:  # pragma: no cover
        # pre-4.6
        scenario_div = cast("Any", test_details_page.find(class_="previous")).div.div
        scenario = re.findall(r"[Rr]esults for (.*) \(", scenario_div.text)[0]
    latest_link = absolute_url(root_url, scenario_div.a)
    try:
        overview = cast("Any", test_details_page.find(id="job_next_previous_table", class_="overview"))
        previous_results = overview.find_all("tr")[1:]
    except AttributeError:  # pragma: no cover
        # pre-4.6
        overview = cast("Any", test_details_page.find(id="previous_results", class_="overview"))
        previous_results = overview.find_all("tr")[1:]
    previous_results_list = [
        (
            str(i.td["id"]),
            {
                "status": status(i),
                "details": get_test_details(i),
                "build": cast("str", i.find(class_="build").text),
            },
        )
        for i in previous_results
    ]
    return TestContext(group, build, scenario, latest_link, previous_results_list)


def _build_report_urls(
    bug_file_loc: str, build: str, module: str, description: str, product_info: tuple[str, str]
) -> tuple[str, str]:
    """Build and return (product_bug_url, test_issue_url) for issue reporting."""
    component, product = product_info
    module_in_desc = f" in {module}" if module else ""
    module_with_space = f"{module} " if module else ""
    product_entries = OrderedDict([
        ("product", product),
        ("component", component),
        ("short_desc", f"[Build {build}] openQA test fails{module_in_desc}"),
        ("bug_file_loc", bug_file_loc),
        ("comment", description),
    ])
    product_bug = (
        urljoin(str(config.get("product_issues", "report_url")), "enter_bug.cgi") + "?" + urlencode(product_entries)
    )
    test_entries = OrderedDict([
        ("issue[subject]", f"[Build {build}] test {module_with_space}fails"),
        ("issue[description]", description),
    ])
    test_issue = config.get("test_issues", "report_url") + "?" + urlencode(test_entries)
    return product_bug, test_issue


# too complex, we might want to remove this function anyway as openQA has it already
def issue_report_link(root_url: str, f: dict[str, Any], test_browser: Browser | None = None) -> str:
    """Generate a bug reporting link for the current issue."""
    # always select the first failed module.
    # It might not be the fatal one but better be safe and assume the first
    # failed module introduces a problem in the whole job

    if test_browser is None:  # pragma: no cover
        msg = "test_browser is required to generate a bug report link"
        raise ValueError(msg)
    test_details_page = test_browser.get_soup(f["href"])
    ctx = _get_test_context(root_url, test_details_page)
    module, url, details = get_failed_module_details_for_report(f)
    abs_url = urljoin(root_url, str(url))
    first_known_bad, last_good = _find_first_last(root_url, ctx.build, ctx.previous_results_list)
    description = _build_issue_description(ctx.scenario, abs_url + details, first_known_bad, last_good, ctx.latest_link)
    product_info = _lookup_component_and_product(root_url, test_details_page, url, module, ctx.group)
    product_bug, test_issue = _build_report_urls(abs_url, ctx.build, module, description, product_info)
    return f": report [product bug]({product_bug}) / [openQA issue]({test_issue})"


def _parse_issue_timestamp(timestamp: str) -> datetime.datetime:
    """Parse the timestamp of a specified redmine issue timestamp field."""
    return datetime.datetime.strptime(timestamp, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=datetime.UTC)


class Issue:
    """Issue with extra status info from issue tracker."""

    def __init__(
        self,
        bugref: str,
        bugref_href: str | None,
        *,
        query_issue_status: bool = False,
        progress_browser: Browser | None = None,
        bugzilla_browser: Browser | None = None,
    ) -> None:
        """Construct an issue object with options."""
        self.bugref = bugref
        self.bugref_href = bugref_href
        bugid_match = re.search(bugref_regex, bugref)
        self.bugid: int | None = int(bugid_match.group(2)) if bugid_match else None
        self.msg: str | None = None
        self.json: dict[str, Any] | None = None
        self.subject: str | None = None
        self.status: str | None = None
        self.assignee: str | None = None
        self.resolution: str | None = None
        self.priority: str | None = None
        self.queried: bool = False
        self.last_comment_date: datetime.datetime | None = None
        self.last_comment_text: str | None = None
        self.last_comment_delay: int = 0
        self.issue_type: str | None = None
        self.error: bool = False
        self.progress_browser: Browser | None = progress_browser
        self.bugzilla_browser: Browser | None = bugzilla_browser
        if query_issue_status and progress_browser and bugzilla_browser:
            log.debug("Retrieving bug data for %s", bugref)
            try:
                match = re.search(f"^{bugref_regex}", self.bugref)
                tracker = match.group(1) if match else None
                if self.bugid == 0:
                    log.debug("#0 ticket id reference found")
                    self.msg = (
                        "NOTE: boo#0/bsc#0/poo#0 label used, please review."
                        " Consider creating progress ticket for the investigation"
                    )
                    return
                if tracker == "poo":
                    self._init_redmine(progress_browser)
                elif tracker in {"boo", "bsc", "bgo"}:
                    self._init_bugzilla(bugzilla_browser)
                else:
                    log.debug('No valid bugref found. Bugref found: "%s"', self.bugref)
                self.queried = True
            except DownloadError as e:  # pragma: no cover
                log.info(
                    "A download error has been encountered for bugref %s (%s): %s",
                    self.bugref,
                    self.bugref_href,
                    e,
                )
                self.msg = str(e)
                self.error = True
            except BugNotFoundError:
                log.exception(
                    "Error retrieving details for bugref %s (%s)",
                    self.bugref,
                    self.bugref_href,
                )
                self.msg = "Ticket not found"
                self.error = True

    def _init_redmine(self, progress_browser: Browser) -> None:
        """Initialize data for redmine issues."""
        log.debug("Test issue discovered, looking on progress")
        self.issue_type = "redmine"
        if self.bugref_href is None:  # pragma: no cover
            msg = "bugref_href is required for redmine issue initialization"
            raise ValueError(msg)
        raw = cast("dict[str, Any]", progress_browser.get_json(self.bugref_href + ".json?include=journals"))
        self.json = cast("dict[str, Any]", raw["issue"])
        self.status = cast("dict[str, Any]", self.json["status"])["name"]
        self.assignee = cast("dict[str, Any]", self.json.get("assigned_to", {"name": "None"}))["name"]
        self.subject = self.json["subject"]
        self.priority = cast("dict[str, Any]", self.json["priority"])["name"]
        self.last_comment_date = _parse_issue_timestamp(cast("str", self.json["updated_on"]))
        self.last_comment_text = ""
        if "journals" in self.json:
            journals = cast("list", self.json["journals"])
            for j in reversed(journals):
                if "notes" not in j:  # pragma: no cover
                    continue
                self.last_comment_text = j["notes"]
                break
            if len(journals) > 1:
                self.last_comment_delay = (
                    self.last_comment_date - _parse_issue_timestamp(cast("dict[str, Any]", journals[-2])["created_on"])
                ).days

    def _init_bugzilla(self, bugzilla_browser: Browser) -> None:
        """Initialize data for bugzilla issues."""
        log.debug("Product bug discovered, looking on bugzilla")
        self.issue_type = "bugzilla"
        ids: dict[str, JsonType] = {"ids": [self.bugid]}
        bug_get_result = cast("dict[str, Any]", bugzilla_browser.json_rpc_get("/jsonrpc.cgi", "Bug.get", ids))
        self.json = cast("list", cast("dict[str, Any]", bug_get_result["result"])["bugs"])[0]
        self.status = cast("dict[str, Any]", self.json)["status"]
        json_dict = cast("dict[str, Any]", self.json)
        if json_dict.get("resolution"):
            self.resolution = json_dict["resolution"]
        self.assignee = json_dict.get("assigned_to", "None")
        self.subject = json_dict["summary"]
        priority_str = cast("str", json_dict["priority"])
        self.priority = priority_str.split(" ")[0] + "/" + cast("str", json_dict["severity"])
        res = cast("dict[str, Any]", bugzilla_browser.json_rpc_get("/jsonrpc.cgi", "Bug.comments", ids))
        result_dict = cast("dict[str, Any]", res["result"])
        bugs_dict = cast("dict[str, Any]", result_dict["bugs"])
        comments = cast("list", bugs_dict[str(self.bugid)]["comments"])
        self.last_comment_date = _parse_issue_timestamp(cast("dict[str, Any]", comments[-1])["creation_time"])
        self.last_comment_text = cast("dict[str, Any]", comments[-1])["text"]
        if len(comments) > 1:
            self.last_comment_delay = (
                self.last_comment_date - _parse_issue_timestamp(cast("dict[str, Any]", comments[-2])["creation_time"])
            ).days

    def add_comment(self, comment: str, status_id: int | None = None) -> None:
        """Add a comment to an issue with RPC/REST operations."""
        log.info("Posting a comment on %s ticket [%s](%s)", self.issue_type, self.bugref, self.bugref_href)
        if self.issue_type == "bugzilla":
            if self.bugzilla_browser is None:  # pragma: no cover
                msg = "bugzilla_browser is required to add a comment to a bugzilla issue"
                raise ValueError(msg)
            self.bugzilla_browser.json_rpc_post(
                "/jsonrpc.cgi",
                "Bug.add_comment",
                {
                    "id": self.bugid,
                    "comment": comment,
                    "is_private": False,
                },
            )
        elif self.issue_type == "redmine":
            if self.progress_browser is None:  # pragma: no cover
                msg = "progress_browser is required to add a comment to a redmine issue"
                raise ValueError(msg)
            if self.bugref_href is None:  # pragma: no cover
                msg = "bugref_href is required to add a comment to a redmine issue"
                raise ValueError(msg)
            issue_data: dict[str, Any] = {"notes": comment}
            if status_id is not None:
                issue_data["status_id"] = status_id
            self.progress_browser.json_rest(self.bugref_href + ".json", "PUT", {"issue": issue_data})
        else:  # pragma: no cover
            msg = "Only bugzilla or redmine supported as issue type"
            raise AssertionError(msg)

    def reopen(self, note: str | None = None) -> None:
        """Re-open issue with RPC/REST operations leaving a note. Only leaves the note if the issue is still open."""
        log.info("Re-opening %s ticket with comment [%s](%s)", self.issue_type, self.bugref, self.bugref_href)
        if note is None:
            note = (
                "Re-opening tickets with unhandled openqa-review reminder comment, see "
                "https://progress.opensuse.org/projects/openqatests/wiki/Wiki#openqa-review-reminder-handling"
            )
        if self.issue_type == "bugzilla":
            if self.bugzilla_browser is None:  # pragma: no cover
                msg = "bugzilla_browser is required to reopen a bugzilla issue"
                raise ValueError(msg)
            if (self.status or "").upper() == "RESOLVED":
                self.bugzilla_browser.json_rpc_post(
                    "/jsonrpc.cgi",
                    "Bug.update",
                    {"ids": [self.bugid], "comment": {"body": note, "is_private": False}, "status": "REOPENED"},
                )
            else:
                self.add_comment(note)
        elif self.issue_type == "redmine":
            status_id = (
                REDMINE_STATUS_ID_FEEDBACK
                if (self.status or "").lower() in {"closed", "rejected", "resolved"}
                else None
            )
            self.add_comment(note, status_id=status_id)
        else:
            msg = "Only bugzilla or redmine supported as issue type"  # pragma: no cover
            raise AssertionError(msg)  # pragma: no cover

    @property
    def is_assigned(self) -> bool:
        """Issue has been assigned."""
        if not self.queried:  # pragma: no cover
            msg = "Issue must be queried before checking assignment"
            raise RuntimeError(msg)
        return not (self.assignee in {"None", None} or "@forge.provo.novell.com" in self.assignee)

    @property
    def is_open(self) -> bool:
        """Issue is still open."""
        if not self.queried:  # pragma: no cover
            msg = "Issue must be queried before checking open state"
            raise RuntimeError(msg)
        s = (self.status or "").upper()
        return s not in {"RESOLVED", "REJECTED", "VERIFIED", "CLOSED"}

    @property
    def last_comment(self) -> tuple[datetime.datetime | None, str | None]:
        """Return datetime object and text of all comments retrieved from an issue."""
        return (self.last_comment_date, self.last_comment_text)

    def __str__(self) -> str:
        """Format issue using markdown."""
        if self.msg:
            msg = self.msg
        elif self.status:
            status = self.status
            if self.resolution:
                status += f" ({self.resolution})"
            if status.startswith(("VERIFIED", "Resolved")):
                status = f'<span style="color: red;">{status}</span>'
            msg = f"Ticket status: {status}, prio/severity: {self.priority}, assignee: {self.assignee}"
        else:
            msg = None

        def _format_all_urls_using_markdown(string: str) -> str:
            url_pattern = r"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
            return re.sub(url_pattern, r"[\g<0>](\g<0>)", string)

        title_str = f' "{self.subject.replace(")", "&#41;")}"' if self.subject else ""
        bugref_str = (
            f"[{self.bugref}]({self.bugref_href}{title_str})"
            if self.bugref_href
            else _format_all_urls_using_markdown(self.bugref)
        )
        msg_str = f" ({msg})" if msg else ""
        return f"{bugref_str}{msg_str}"


class IssueEntry:
    """List of failed test scenarios with corresponding bug."""

    def __init__(
        self,
        args: argparse.Namespace,
        root_url: str,
        failures: list[dict[str, Any]],
        test_browser: Browser | None = None,
        bug: Issue | None = None,
    ) -> None:
        """Construct an issueentry object with options."""
        self.args = args
        self.failures = list(failures)
        self.bug = bug
        self.soft = self.failures[0]["state"] in soft_fail_states
        self.root_url = root_url
        self.test_browser = test_browser

    def url(self, v: dict[str, Any]) -> str:
        """Absolute url e.g. for test references."""
        return absolute_url(self.root_url, v)

    @staticmethod
    def _format_failure_modules(failedmodules: list[dict[str, Any]]) -> str:
        return ", ".join(m["name"] for m in failedmodules)

    def _format_failure(self, f: dict[str, Any]) -> str:
        """Yield a report entry for one new issue based on verbosity."""
        failure_modules_str = (
            f' "Failed modules: {self._format_failure_modules(f["failedmodules"])}"' if f["failedmodules"] else ""
        )
        report_str = (
            issue_report_link(self.root_url, f, self.test_browser)
            if (self.args.report_links and self.test_browser)
            else ""
        )
        if self.args.verbose_test >= VERBOSE_TEST_CHANGES and "prev" in f:
            return (
                f"[{f['name']}]({self.url(f)}{failure_modules_str})"
                f' [(ref)]({self.url(f["prev"])} "Previous test"){report_str}'
            )
        if self.args.verbose_test >= VERBOSE_TEST_REF_BUILD:
            return f"[{f['name']}]({self.url(f)}{failure_modules_str}){report_str}"
        return f["name"]

    def stringify(self) -> str:
        """Return as markdown."""
        bug_suffix = f" -> {self.bug}" if self.bug else ""
        test_bug_str = f"{', '.join(map(self._format_failure, self.failures))}{bug_suffix}"
        short_str = self.bug or ", ".join(i["name"] for i in self.failures)
        prefix = "soft fails: " if self.soft else ""
        return f"{prefix}{short_str if self.args.short_failure_str else test_bug_str}"

    def __str__(self) -> str:
        """Return as markdown list item."""
        return "* " + self.stringify() + "\n"

    @classmethod
    def for_each(
        cls, args: argparse.Namespace, root_url: str, failures: Iterable[dict[str, Any]], test_browser: Browser | None
    ) -> Generator[IssueEntry, None, None]:
        """Create one object for each failure (for todo entries)."""
        return (cls(args, root_url, [f], test_browser) for f in failures)


def get_skipped_dict(arch: str, soup: BeautifulSoupType) -> SortedDictType:
    """Get a dict of the skipped tests per arch parsing the bs4 instance."""
    re_arch = re.compile(arch + "_")
    arch_findings = soup.find_all("td", id=re_arch)
    results = SortedDict()
    for arch_item in arch_findings:
        match = arch_item.find(title="cancelled")
        if match:
            name_tag = arch_item.find_previous(class_="name")
            if name_tag is None:  # pragma: no cover
                msg = "Could not find name tag for skipped test entry"
                raise ValueError(msg)
            module_name = name_tag.get_text().strip("\n")
            a_tag = arch_item.a
            if a_tag is None:  # pragma: no cover
                msg = "Could not find <a> tag in skipped test arch item"
                raise ValueError(msg)
            test_link = str(a_tag["href"])
            results.update({module_name: test_link})
    return results


def format_skipped_output(findings: SortedDictType, root_url: str) -> list[str]:
    """Format the output as a markdown page for each skipped test."""
    return [f"* [{k}]({''.join([root_url[:-1], v])})\n" for k, v in findings.items()]


class ArchReport:
    """Report for a single architecture."""

    def __init__(
        self, arch: str, results: SortedDictType, args: argparse.Namespace, root_url: str, browsers: BrowserSet
    ) -> None:
        """Construct an archreport object with options."""
        self.arch = arch
        self.args = args
        self.root_url = root_url
        self.progress_browser = browsers.progress_browser
        self.bugzilla_browser = browsers.bugzilla_browser
        self.test_browser = browsers.test_browser
        self.skipped_tests = format_skipped_output(results.pop("skipped"), self.root_url)
        self.status_badge = set_status_badge([i["state"] for i in results.values()])
        if self.args.bugrefs and self.args.include_softfails:
            self._search_for_bugrefs_for_softfailures(results)

        # if a ticket is known and the same refers to a STILL_FAILING scenario and any NEW_ISSUE we regard that as
        # STILL_FAILING but just visible in more scenarios, ...
        # ... else (no ticket linked) we don't group them as we don't know if it really is the same issue and handle
        # them outside
        results_by_bugref = SortedDict(get_results_by_bugref(results, self.args))
        self.issues = defaultdict(lambda: defaultdict(list))
        for bugref, result_list in results_by_bugref.items():
            if bugref.startswith("todo"):
                log.info("Skipping \"todo\" bugref '%s' in '%s'", bugref, result_list)
                continue
            bug = result_list[0]
            issue = Issue(
                bug["bugref"],
                bug.get("bugref_href", None),
                query_issue_status=self.args.query_issue_status,
                progress_browser=self.progress_browser,
                bugzilla_browser=self.bugzilla_browser,
            )
            self.issues[issue_state(result_list)][issue_type(bugref)].append(
                IssueEntry(self.args, self.root_url, result_list, bug=issue)
            )

        # left to handle are the issues marked with 'todo'
        todo_results = results_by_bugref.get("todo", [])
        new_issues = (r for r in todo_results if r["state"] == "NEW_ISSUE")
        self.issues["new"]["todo"].extend(IssueEntry.for_each(self.args, self.root_url, new_issues, self.test_browser))
        existing_issues = (r for r in todo_results if r["state"] == "STILL_FAILING")
        self.issues["existing"]["todo"].extend(
            IssueEntry.for_each(self.args, self.root_url, existing_issues, self.test_browser)
        )
        if self.args.include_softfails:
            new_soft_fails = [r for r in todo_results if r["state"] == "NEW_SOFT_ISSUE"]
            existing_soft_fails = [r for r in todo_results if r["state"] == "STILL_SOFT_FAILING"]
            if new_soft_fails:
                self.issues["new"]["product"].append(IssueEntry(self.args, self.root_url, new_soft_fails))
            if existing_soft_fails:
                self.issues["existing"]["product"].append(IssueEntry(self.args, self.root_url, existing_soft_fails))

    @staticmethod
    def _apply_softfailure_bugref(
        v: dict[str, Any],
        match: re.Match[str] | str,
        softfail_reason: str | None,
        *,
        found_actual_ref: bool,
    ) -> None:
        if not found_actual_ref:
            v["bugref"] = match
            v["softfail_reason"] = softfail_reason
            return
        actual_match = cast("re.Match[str]", match)
        bug_tracker, bug_id = actual_match.group(1), actual_match.group(2)
        if not bug_tracker:  # pragma: no cover
            msg = f"No bugref found for {v}"
            raise ValueError(msg)
        if not bug_id:  # pragma: no cover
            msg = f"No bug_id found for {v}"
            raise ValueError(msg)
        v["bugref"] = f"{bug_tracker}#{bug_id}"
        v["bugref_href"] = issue_tracker[bug_tracker](bug_id)
        v["softfail_reason"] = softfail_reason

    def _search_for_bugrefs_for_softfailures(self, results: SortedDictType) -> None:
        for v in results.values():
            if v["state"] in soft_fail_states:
                try:
                    module_url = self._get_url_to_softfailed_module(v["href"])
                    if module_url is None:  # pragma: no cover
                        msg = f"Could not determine softfailed module URL for job {v['href']}"
                        raise ValueError(msg)
                    url_match = re.search(r"[^/]*/[0-9]*/[^/]*/([^/]*)/[^/]*/[0-9]*", module_url)
                    if url_match is None:  # pragma: no cover
                        msg = f"Could not parse module URL: {module_url}"
                        raise ValueError(msg)
                    module_name = url_match.group(1)
                    if not module_name:  # pragma: no cover
                        msg = f"could not find a module name within {module_url} in job {v['href']}"
                        raise ValueError(msg)
                    match, softfail_reason, found_actual_ref = self._get_bugref_for_softfailed_module(v, module_name)
                except (AttributeError, KeyError, IndexError, StopIteration):
                    log.info(
                        "Could find neither soft failed info box nor needle, assuming an old openQA job, skipping."
                    )
                    continue
                except DownloadError:  # pragma: no cover
                    log.exception("Failed to process %s. Skipping current result", v)
                    continue
                self._apply_softfailure_bugref(v, match, softfail_reason, found_actual_ref=found_actual_ref)

    @property
    def total_issues(self) -> int:
        """Return Number of issue entries for this arch."""
        total = 0
        for issue_types in self.issues.values():
            for ies in issue_types.values():
                total += len(ies)
        return total

    def _get_url_to_softfailed_module(self, job_url: str) -> str | None:
        log.debug("job_url %s", job_url)
        if self.test_browser is None:  # pragma: no cover
            msg = "test_browser is required to get softfailed module URL"
            raise ValueError(msg)
        try:
            raw_details = cast(
                "dict[str, Any]",
                self.test_browser.get_json("/api/v1/jobs/" + job_url.rsplit("/", maxsplit=1)[-1] + "/details"),
            )
            # fake an older module URL including the name, see https://progress.opensuse.org/issues/72292
            testresults = cast("list", cast("dict[str, Any]", raw_details["job"])["testresults"])
            name = next(i for i in testresults if cast("dict[str, Any]", i)["result"] == "softfailed")
            name = cast("dict[str, Any]", name)["name"]
        except DownloadError:
            log.debug("Found older openQA, before https://github.com/os-autoinst/openQA/pull/2932")
        else:
            return f"///{name}//"
        url = job_url
        test_details_html = self.test_browser.get_soup(url).find(title="Soft Failed")
        if test_details_html is None:
            log.debug("Could not find soft failed info box, looking for workaround needle in job %s", url)
            resborder_tag = self.test_browser.get_soup(url).find(class_="resborder_softfailed")
            if resborder_tag is None:  # pragma: no cover
                msg = f"Could not find resborder_softfailed element in job {url}"
                raise ValueError(msg)
            test_details_html = resborder_tag.parent
        if not test_details_html:  # pragma: no cover
            msg = "Found neither soft failed info box nor workaround needle"
            raise RuntimeError(msg)
        return cast("str | None", test_details_html.get("data-url"))

    @staticmethod
    def _is_workaround_needle(field: dict[str, Any]) -> bool:
        return (
            "properties" in field
            and "needle" in field
            and len(cast("list", field["properties"])) > 0
            and cast("list", field["properties"])[0] == "workaround"
        )

    def _get_bugref_for_softfailed_module(
        self, result_item: dict[str, Any], module_name: str
    ) -> tuple[re.Match[str] | str, str | None, bool]:
        rel_job_url = result_item["href"]
        details_url = f"{rel_job_url}/file/details-{quote(module_name)}.json"
        log.debug("Retrieving '%s'", details_url)
        if self.test_browser is None:  # pragma: no cover
            msg = "test_browser is required to get bugref for softfailed module"
            raise ValueError(msg)
        details_json = self.test_browser.get_json(details_url)
        raw_list: list = (
            cast("dict[str, Any]", details_json)["details"]
            if isinstance(details_json, dict) and "details" in details_json
            else cast("list", details_json)
        )
        for raw_field in raw_list:
            field = cast("dict[str, Any]", raw_field)
            result = self._match_bugref_in_field(field, rel_job_url)
            if result is not None:
                return result
        return ("missing/unsupported bug reference", None, False)

    def _match_bugref_in_field(
        self, field: dict[str, Any], rel_job_url: str
    ) -> tuple[re.Match[str] | str, str | None, bool] | None:
        if self.test_browser is None:  # pragma: no cover
            msg = "test_browser is required"
            raise ValueError(msg)
        match = None
        softfail_reason = None
        if "title" in field and "Soft Fail" in field["title"]:
            unformatted_str = (
                field["text_data"]
                if "text_data" in field
                else self.test_browser.get_soup(f"{rel_job_url}/file/{quote(field['text'])}").getText()
            )
            match = re.search(bugref_regex, unformatted_str)
            softfail_reason = unformatted_str
            if not match:  # use the "Soft Failure: …" text as bugref instead
                match = re.search(r"Soft Failure:\n(.*)", unformatted_str.strip())
                if match:
                    return (match.group(1), softfail_reason, False)
        # custom results can have soft-fail as well
        elif "result" in field and "title" in field and "softfail" in field["result"]:
            match = re.search(bugref_regex, field["title"])
            softfail_reason = field.get("text_data", field["title"])
        elif self._is_workaround_needle(field):
            log.debug("Evaluating potential workaround needle '%s'", field["needle"])
            match = re.search(bugref_regex, field["needle"])
            if not match:  # pragma: no cover
                log.warning(
                    "Found workaround key without bugref that could be understood,"
                    " looking for a better bugref (if any) for '%s'",
                    rel_job_url,
                )
                return None
        if match:
            return (match, softfail_reason, True)
        return None

    def has_todo_issues(self) -> bool:
        """Tell if report has new or existing todo issues."""
        return self.issues["new"]["todo"] or self.issues["existing"]["todo"]

    def _todo_issues_str(self) -> str:
        if self.args.abbreviate_test_issues:
            return issue_listing(
                "### Test issues",
                self.issues["new"]["openqa"]
                + self.issues["existing"]["openqa"]
                + self.issues["new"]["todo"]
                + self.issues["existing"]["todo"],
                show_empty=self.args.show_empty,
            )
        if not self.has_todo_issues():
            return ""

        if self.args.todo_only:
            return issue_listing(
                "**new**", self.issues["new"]["todo"], show_empty=self.args.show_empty, no_headers=True
            ) + issue_listing(
                "**existing**", self.issues["existing"]["todo"], show_empty=self.args.show_empty, no_headers=True
            )
        return todo_review_template.substitute({
            "new_issues": issue_listing(
                "***new issues***", self.issues["new"]["todo"], show_empty=self.args.show_empty
            ),
            "existing_issues": issue_listing(
                "***existing issues***", self.issues["existing"]["todo"], show_empty=self.args.show_empty
            ),
        })

    def __str__(self) -> str:
        """Return as markdown."""
        abbrev = self.args.abbreviate_test_issues
        if self.args.todo_only:
            return self._todo_issues_str() if self.has_todo_issues() else ""

        return openqa_review_report_arch_template.substitute({
            "arch": self.arch,
            "status_badge": status_badge_str[self.status_badge],
            # everything that is 'NEW_ISSUE' should be product issue but if tests have changed content, then
            # probably openqa issues For now we can just not easily decide unless we use the 'bugrefs' mode
            "new_openqa_issues": (
                ""
                if abbrev
                else issue_listing(
                    "**New openQA-issues:**", self.issues["new"]["openqa"], show_empty=self.args.show_empty
                )
            ),
            "existing_openqa_issues": (
                ""
                if abbrev
                else issue_listing(
                    "**Existing openQA-issues:**", self.issues["existing"]["openqa"], show_empty=self.args.show_empty
                )
            ),
            "new_product_issues": issue_listing(
                "**New Product bugs:**", self.issues["new"]["product"], show_empty=self.args.show_empty
            ),
            "existing_product_issues": issue_listing(
                "**Existing Product bugs:**", self.issues["existing"]["product"], show_empty=self.args.show_empty
            ),
            "todo_issues": self._todo_issues_str(),
            "skipped_tests": issue_listing("**Skipped tests:**", self.skipped_tests, show_empty=self.args.show_empty),
        })


class ProductReport:
    """Read overview page of one job group and generate a report for the product."""

    def __init__(self, browser: Browser, job_group_url: str, root_url: str, args: argparse.Namespace) -> None:
        """Construct a product report object with options."""
        self.args = args
        self.job_group_url = job_group_url
        self.group = job_group_url.rsplit("/", maxsplit=1)[-1]
        current_url, previous_url = get_build_urls_to_compare(
            browser, job_group_url, args.builds, args.against_reviewed, args.running_threshold
        )
        # read last finished
        current_details = browser.get_soup(current_url)
        previous_details = browser.get_soup(previous_url)
        for details in current_details, previous_details:
            # build pages matching no tests show no job as well as builds only consisting of incomplete jobs
            # see https://progress.opensuse.org/issues/60458
            if not (
                sum(int(badge.text) for badge in details.find_all(class_="badge")) > 0
                or len(details.find_all(class_="status")) > 0
            ):  # pragma: no cover
                msg = (
                    f"invalid page with no test results found reading {current_url} and {previous_url},"
                    " make sure you specified valid builds (leading zero missing?)"
                )
                raise ValueError(msg)
        current_summary = parse_summary(current_details)
        previous_summary = parse_summary(previous_details)

        changes = SortedDict({k: v - previous_summary.get(k, 0) for k, v in current_summary.items()})
        self.changes_str = (
            "***Changes since reference build***\n\n* " + "\n* ".join(f"{k}: {v}" for k, v in changes.items()) + "\n"
        )
        log.info("%s", self.changes_str)

        self.build = get_build_nr(current_url)
        self.ref_build = get_build_nr(previous_url)

        # for each architecture iterate over all
        cur_archs, prev_archs = (
            {arch.text for arch in details.find_all("th", id=re.compile(r"flavor_"))}
            for details in [current_details, previous_details]
        )
        archs = cur_archs
        if args.arch:
            if args.arch not in cur_archs:  # pragma: no cover
                msg = f"Selected arch {args.arch} was not found in test results {cur_archs}"
                raise ValueError(msg)
            archs = [args.arch]
        self.missing_archs = sorted(prev_archs - cur_archs)
        if self.missing_archs:
            log.info(
                "%s missing completely from current run: %s",
                pluralize(len(self.missing_archs), "architecture is", "architectures are"),
                ", ".join(self.missing_archs),
            )

        # create arch reports
        self.reports = SortedDict()
        progress_browser = progress_browser_factory(args) if args.query_issue_status else None
        bugzilla_browser = bugzilla_browser_factory(args) if args.query_issue_status else None
        for arch in sorted(archs):
            results = get_arch_state_results(
                arch, current_details, previous_details, output_state_results=args.output_state_results
            )
            browsers = BrowserSet(progress_browser, bugzilla_browser, browser)
            self.reports[arch] = ArchReport(arch, results, args, root_url, browsers)

    def __str__(self) -> str:
        """Return report for product."""
        now_str = datetime.datetime.now(tz=datetime.UTC).strftime("%Y-%m-%d - %H:%M")
        missing_archs_str = (
            f"\n * **Missing architectures**: {', '.join(self.missing_archs)}" if self.missing_archs else ""
        )

        build_str = self.build
        if self.args.verbose_test and self.args.verbose_test > VERBOSE_TEST_REF_BUILD - 1:
            build_str += f" (reference {self.ref_build})"
        if self.args.verbose_test and self.args.verbose_test > VERBOSE_TEST_CHANGES:
            build_str += "\n\n" + self.changes_str

        arch_reports = [v for v in self.reports.values() if not self.args.skip_passed or v.status_badge != "GREEN"]
        archreports = [i for i in map(str, arch_reports) if len(i)]
        if len(archreports) == 0:
            return ""
        if self.args.todo_only:
            return "".join(archreports)
        return openqa_review_report_product_template.substitute({
            "now": now_str,
            "build": build_str,
            "common_issues": common_issues(missing_archs_str, show_empty=self.args.show_empty),
            "arch_report": "\n---\n".join(archreports),
        })

    def is_passed(self) -> bool:
        """Return True if none of the reports contain failures."""
        return all(v.status_badge == "GREEN" for v in self.reports.values())


class CustomFormatter(argparse.ArgumentDefaultsHelpFormatter, argparse.RawDescriptionHelpFormatter):
    """Preserve multi-line __doc__ and provide default arguments in help strings."""


def parse_args() -> argparse.Namespace:
    """Parse and return command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=CustomFormatter)
    parser.add_argument(
        "-v",
        "--verbose",
        help="Increase verbosity level, specify multiple times to increase verbosity",
        action="count",
        default=1,
    )
    parser.add_argument(
        "-n", "--no-progress", action="store_true", help="Be terse and only output the report, no progress indication"
    )
    parser.add_argument(
        "-s",
        "--output-state-results",
        action="store_true",
        help='Additional plain text output of arch-specific state results, e.g. all NEW_ISSUE; on for "verbose" mode',
    )
    parser.add_argument("--host", default="https://openqa.opensuse.org", help="openQA host to access")
    parser.add_argument(
        "-j",
        "--job-groups",
        help="""Only handle selected job group(s), comma separated, e.g. \'openSUSE Tumbleweed Gnome\'.
                        A regex also works, e.g. \'openSUSE Tumbleweed\' or \'(Gnome|KDE)\'.""",
    )
    parser.add_argument(
        "--exclude-job-groups", help="""Exclude selected job groups by regex, inverse of '--job-groups'."""
    )
    parser.add_argument(
        "-J",
        "--job-group-urls",
        help="""Only handle selected job group(s) specified by URL, comma separated. Overwrites "--host" argument.
                        Skips parsing on main page and can actually save some seconds.""",
    )
    builds = parser.add_mutually_exclusive_group()
    builds.add_argument(
        "-b",
        "--builds",
        help="""Select explicit builds, comma separated.
                        Specify as unambiguous search terms, e.g. build number,
                        the full string, etc. Only works with single job-group/job-group-urls.
                        Default 'last' and 'previous'.""",
    )
    builds.add_argument(
        "-B",
        "--against-reviewed",
        metavar="BUILD",
        help="""Compare specified build against last reviewed (as found in comments section).
                        E.g. if the last reviewed job was '0123' and you want to compare build '0128' against '0123',
                        specify just '0128' and the last reviewed job is found from the comments section if the comment
                        is sticking to the template format for review comments.
                        Special argument 'last' will compare the last finished build against the last reviewed one.""",
    )
    parser.add_argument(
        "-T",
        "--verbose-test",
        help="Increase test result verbosity level, specify multiple times to increase verbosity",
        action="count",
        default=1,
    )
    parser.add_argument(
        "-r",
        "--bugrefs",
        action="store_true",
        help="""Parse \'bugrefs\' from test results comments and triage issues accordingly.
                        See https://progress.opensuse.org/projects/openqav3/wiki/Wiki#Show-bug-or-label-icon-on-overview-if-labeled-gh550
                        for details about bugrefs in openQA""",
    )
    parser.add_argument(
        "--short-failure-str",
        action="store_true",
        help=(
            "Instead of the default long failure description use a short version only outputting"
            " the referenced bug or the failing test in case of failure without bugref."
        ),
    )
    parser.add_argument(
        "--abbreviate-test-issues",
        action="store_true",
        help=(
            "If requested abbreviate all 'test issue' related reporting sections and instead only show"
            " a short list of these next to the full-detail product issues."
            " Useful to focus on product-related reports."
        ),
    )
    parser.add_argument(
        "-R",
        "--query-issue-status",
        action="store_true",
        help=(
            f'Query issue trackers for the issues found and report on their status and assignee. Implies "-r/--bugrefs"'
            f" and needs configuration file {CONFIG_PATH} with credentials, see '--query-issue-status-help'."
        ),
    )
    parser.add_argument(
        "--query-issue-status-help",
        action="store_true",
        help="""Shows help how to setup '--query-issue-status' configuration file.""",
    )
    parser.add_argument(
        "--report-links",
        action="store_true",
        help="""Generate issue reporting links into report. Needs configuration file for product mapping,
                        see '--query-issue-status-help'.""",
    )
    parser.add_argument("-a", "--arch", help="Only single architecture, e.g. 'x86_64', not all")
    parser.add_argument("-f", "--filter", help="Filter for 'closed' or 'unassigned' issues.")
    parser.add_argument(
        "--running-threshold",
        default=0,
        help="Percentage of jobs that may still be running for the build to be considered 'finished' anyway",
    )
    parser.add_argument(
        "--no-empty-sections",
        action="store_false",
        default=True,
        dest="show_empty",
        help="Only show sections in report with content",
    )
    parser.add_argument(
        "--skip-passed",
        action="store_true",
        default=False,
        dest="skip_passed",
        help="Skip passed reports",
    )
    parser.add_argument(
        "--todo-only",
        action="store_true",
        default=False,
        dest="todo_only",
        help="List only TODO items as one liners",
    )
    parser.add_argument(
        "--include-softfails",
        action="store_true",
        default=False,
        help="""Also include softfails in reports.
                        Not included by default as less important and there is
                        no carry over for soft fails, i.e. there are no
                        bugrefs attached to these failures in most cases but
                        they should already carry bug references by other
                        means anyway.""",
    )
    reminder_comments = parser.add_argument_group("Reminder comments on found issues")
    reminder_comments.add_argument(
        "--reminder-comment-on-issues",
        action="store_true",
        default=False,
        help=(
            "Go through bugrefs and write an actual comment on the ticket with a corresponding"
            " current job URL in the ticket if it has not been updated for some time."
            " Implies '--query-issue-status'."
        ),
    )
    reminder_comments.add_argument(
        "--dry-run", action="store_true", default=False, help="""Do not actually change any tickets."""
    )
    reminder_comments.add_argument(
        "--min-days-unchanged",
        default=MIN_DAYS_UNCHANGED,
        help=(
            "The minimum period of days that need to be passed since the last comment for the bug to be reminded upon."
        ),
    )
    reminder_comments.add_argument(
        "--no-exponential-backoff",
        action="store_true",
        default=False,
        help="""Disable exponential backoff algorithm for reminders.""",
    )
    reminder_comments.add_argument(
        "--no-reminder-on",
        dest="ignore_pattern",
        type=re.compile,
        default=NO_REMINDER_REGEX,
        help="""A regular expression which will suppress sending the reminder on match.""",
    )
    reminder_comments.add_argument(
        "--reopen",
        default="redmine",
        help=(
            "Select which closed issues to reopen with 'all', 'none' or specific issue types,"
            " e.g 'redmine' or 'bugzilla'."
        ),
    )
    add_browser_args(parser)
    args = parser.parse_args()
    if args.query_issue_status_help:
        log.info(CONFIG_USAGE)
        log.info("Expected file path: %s", CONFIG_PATH)
        sys.exit(0)
    if args.reminder_comment_on_issues:
        args.query_issue_status = True
    if args.query_issue_status:
        args.bugrefs = True
    return args


def get_parent_job_groups(browser: Browser, root_url: str, args: argparse.Namespace) -> dict[int, str]:
    """Retrieve and return a dict of parent job group IDs to names."""
    pgroup_api_url = urljoin(root_url, "api/v1/parent_groups")
    if args.no_progress or not humanfriendly_available:
        response = browser.get_json(pgroup_api_url)
    else:
        with AutomaticSpinner(label="Retrieving parent job groups"):
            response = browser.get_json(pgroup_api_url)
    return {cast("dict[str, Any]", p)["id"]: cast("dict[str, Any]", p)["name"] for p in cast("list", response)}


def get_job_groups(browser: Browser, root_url: str, args: argparse.Namespace) -> SortedDictType:
    """Retrieve and return a SortedDict of job group names to URLs."""
    if args.job_group_urls:
        job_group_urls = args.job_group_urls.split(",")
        log.info("Acting on specified job group URL(s): %s", ", ".join(job_group_urls))
        job_groups = dict(enumerate(job_group_urls))
    else:
        parent_groups = get_parent_job_groups(browser, root_url, args)
        if args.no_progress or not humanfriendly_available:
            results = browser.get_json(urljoin(root_url, "api/v1/job_groups"))
        else:
            with AutomaticSpinner(label="Retrieving job groups"):
                results = browser.get_json(urljoin(root_url, "api/v1/job_groups"))

        def _pgroup_prefix(group: dict[str, Any]) -> str:
            try:
                return f"{parent_groups[group['parent_id']]} / {group['name']}"
            except KeyError:
                return group["name"]

        job_groups = {}
        for raw_job_group in cast("list", results):
            job_group = cast("dict[str, Any]", raw_job_group)
            job_groups[_pgroup_prefix(job_group)] = urljoin(root_url, f"/group_overview/{job_group['id']:d}")
        if args.job_groups:
            job_pattern = re.compile("({})".format("|".join(args.job_groups.split(","))))
            job_groups = {k: v for k, v in job_groups.items() if job_pattern.search(k)}
            log.info("Job group URL for %s: %s", args.job_groups, job_groups)
        if args.exclude_job_groups:
            job_pattern = re.compile("({})".format("|".join(args.exclude_job_groups.split(","))))
            job_groups = {k: v for k, v in job_groups.items() if not job_pattern.search(k)}
            log.info("Job group URL excluding %s: %s", args.exclude_job_groups, job_groups)
    return SortedDict(job_groups)


class Report:
    """openQA review report."""

    def __init__(self, browser: Browser, args: argparse.Namespace, root_url: str, job_groups: SortedDictType) -> None:
        """Create openQA review report."""
        self.browser = browser
        self.args = args
        self.root_url = root_url
        self.job_groups = job_groups

        self._label = "Gathering data and processing report"
        self._progress = 0
        self.report = SortedDict()

        for k, v in job_groups.items():
            log.info("Processing '%s'", v)
            if args.no_progress or not humanfriendly_available:
                self.report[k] = self._one_report(v)
            else:
                with AutomaticSpinner(label=self._next_label()):
                    self.report[k] = self._one_report(v)
            self._progress += 1
        if not args.no_progress:
            sys.stderr.write(f"\r{self._next_label()}\n")  # It's nice to see 100%, too :-)

    def _one_report(self, job_group_url: str) -> ProductReport | str:
        # for each job group on openqa.opensuse.org
        try:
            return ProductReport(self.browser, job_group_url, self.root_url, self.args)
        except NotEnoughBuildsError as e:
            log.debug("Caught 'not enough builds': %s", e)
            return "" if self.args.todo_only else "Not enough finished builds found"

    def _next_label(self) -> str:
        return f"{self._label} {int(self._progress * 100 / len(self.job_groups))}%"

    def __str__(self) -> str:
        """Generate markdown."""
        report_str = ""
        if self.args.todo_only:
            report_str = "**TODO: review**\n\n"
        for k, v in self.report.items():
            if not self.args.skip_passed or type(v) is not ProductReport or not v.is_passed():
                generated = str(v)
                if not len(generated):
                    continue
                report_str += f"### {k}\n{generated}\n" if self.args.todo_only else f"# {k}\n\n{generated}\n---\n"
        return report_str


def generate_report(args: argparse.Namespace) -> Report:
    """Generate and return the full review report."""
    verbose_to_log = {0: logging.CRITICAL, 1: logging.ERROR, 2: logging.WARNING, 3: logging.INFO, 4: logging.DEBUG}
    logging_level = logging.DEBUG if args.verbose > VERBOSE_LEVEL_DEBUG else verbose_to_log[args.verbose]
    log.setLevel(logging_level)
    log.debug("args: %s", args)
    args.output_state_results = args.verbose > 1 or args.output_state_results

    if args.job_group_urls:
        root_url = urljoin("/".join(args.job_group_urls.split("/")[0:3]), "/")
    else:
        root_url = urljoin(str(args.host), "/")

    browser = Browser(args, root_url)
    job_groups = get_job_groups(browser, root_url, args)
    if args.builds and len(job_groups) > 1:  # pragma: no cover
        msg = "builds option and multiple job groups not supported"
        raise AssertionError(msg)
    if len(job_groups) == 0:
        msg = "No job groups were found, maybe misspecified '--job-groups'?"
        raise AssertionError(msg)
    return Report(browser, args, root_url, job_groups)


def load_config() -> None:
    """Load configuration from the config file into the module-level config object."""
    config_entries = config.read(CONFIG_PATH)
    if not config_entries:  # pragma: no cover
        log.error("Need configuration file '%s' for issue retrieval credentials", CONFIG_PATH)
        log.error(CONFIG_USAGE)
        sys.exit(1)


ie_filters = {
    "closed": lambda ie: ie.bug and ie.bug.queried and not ie.bug.is_open,
    "unassigned": lambda ie: ie.bug and ie.bug.queried and ie.bug.is_open and not ie.bug.is_assigned,
}


def filter_report(report: Report, iefilter: Callable[..., bool]) -> None:
    """Filter the report in-place to only include issue entries matching iefilter."""
    report.report = SortedDict({p: pr for p, pr in report.report.items() if isinstance(pr, ProductReport)})
    for pr in report.report.values():
        for ar in pr.reports.values():
            for issue_types in ar.issues.values():
                for itype, ies in issue_types.items():
                    issue_types[itype] = [ie for ie in ies if iefilter(ie)]
        pr.reports = SortedDict({a: ar for a, ar in pr.reports.items() if ar.total_issues > 0})
    report.report = SortedDict({p: pr for p, pr in report.report.items() if pr.reports})


def reminder_comment_on_issue(ie: IssueEntry, args: argparse.Namespace) -> None:
    """Post a reminder comment on a single issue if it has been unchanged long enough."""
    issue = ie.bug
    if issue is None or issue.error or not issue.issue_type:
        return
    if ie.soft and len(ie.failures) > 0 and "softfail_reason" in ie.failures[0]:
        reason = ie.failures[0]["softfail_reason"]
        if reason and args.ignore_pattern and re.search(args.ignore_pattern, reason):
            return
    (last_comment_date, last_comment_text) = issue.last_comment
    if last_comment_date is None:  # pragma: no cover
        return
    threshold = (
        args.min_days_unchanged
        if args.no_exponential_backoff
        else max(2 * issue.last_comment_delay, args.min_days_unchanged)
    )
    if (datetime.datetime.now(tz=datetime.UTC) - last_comment_date).days >= threshold:
        f = ie.failures[0]
        link_to_module = (
            f["failedmodules"][0]["href"]
            if "failedmodules" in f and f["failedmodules"] and "href" in f["failedmodules"][0]
            else None
        )
        if last_comment_text and re.search(re.escape(ie.url(f)), last_comment_text):
            return
        next_threshold = args.min_days_unchanged if args.no_exponential_backoff else 2 * threshold
        pattern = {
            "name": f["name"],
            "url": urljoin(ie.url(f), link_to_module),
            "time_next": next_threshold,
            "no_reminder_pattern": args.ignore_pattern.pattern,
        }
        comment = openqa_issue_comment.substitute(pattern).strip()
        if args.reopen in {"all", issue.issue_type}:
            issue.reopen(comment)


def _iter_issue_entries(report: Report) -> Generator[IssueEntry, None, None]:
    """Yield all IssueEntry objects from a report.

    Yields:
        IssueEntry: each issue entry found across all product and arch reports.

    """
    for pr in report.report.values():
        for ar in pr.reports.values():
            for issue_types in ar.issues.values():
                for ies in issue_types.values():
                    yield from ies


def _process_reminder_for_entry(ie: IssueEntry, args: argparse.Namespace, processed_issues: set[str]) -> None:
    """Post a reminder comment for ie if its bug is new and not yet processed."""
    issue = ie.bug
    if not issue:
        return
    bugref = issue.bugref.replace("bnc", "bsc").replace("boo", "bsc")
    if bugref in processed_issues:
        return
    try:
        reminder_comment_on_issue(ie, args)
    except HTTPError:  # pragma: no cover
        log.exception(
            "Encountered error trying to post a reminder comment on issue '%s'. Skipping.",
            ie,
        )
        return
    processed_issues.add(bugref)


def reminder_comment_on_issues(report: Report, args: argparse.Namespace) -> None:
    """Post reminder comments on all qualifying issues found in the report."""
    processed_issues = set()
    report.report = SortedDict({p: pr for p, pr in report.report.items() if isinstance(pr, ProductReport)})
    for ie in _iter_issue_entries(report):
        _process_reminder_for_entry(ie, args, processed_issues)


def main() -> None:  # pragma: no cover, only interactive
    """Entry point: parse args, generate and print the review report."""
    args = parse_args()
    if args.query_issue_status or args.report_links:
        load_config()
    report = generate_report(args)

    if args.reminder_comment_on_issues:
        reminder_comment_on_issues(report, args)

    if args.filter:
        if args.filter not in ie_filters:
            log.error("No such filter '%s'", args.filter)
            log.error("Available filters: %s", ", ".join(ie_filters.keys()))
            sys.exit(1)
        filter_report(report, ie_filters[args.filter])

    try:
        sys.stdout.write(str(report) + "\n")
    except UnicodeEncodeError:
        log.exception("Encountered UnicodeEncodeError")
        log.exception("type of 'report': %s", type(report))
        log.exception("Trying workaround, explicit utf8 writer to stdout")
        utf8writer = codecs.getwriter("utf8")
        sys.stdout = utf8writer(sys.stdout)
        sys.stdout.write(str(report) + "\n")


if __name__ == "__main__":
    main()
