name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.11'
        - '3.12'
        - '3.13'
        - '3.14'
        include:
          - os: "ubuntu-latest"

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Run test suite
      run: uv run tox -e py$(echo ${{ matrix.python-version }} | tr -d .)
      env:
        PYTEST_ADDOPTS: "-vv --durations=10"

  extra:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type:
        - ruff
        - doctests
        - cov

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6

    - run: uv run tox -e ${{ matrix.test-type }}
    - run: ./.tox/cov/bin/coverage html
      # Run even if previous step failed but only if we are testing coverage
      if: ${{ always() && matrix.test-type == 'cov' }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
      with:
        name: coverage
        path: coverage_html/
      if: ${{ always() && matrix.test-type == 'cov' }}
